server:
   port: 9002
   netty:
      connection-timeout: 10s
      idle-timeout: 15s
   shutdown: graceful

spring:
   application:
      name: order-service
   lifecycle:
      timeout-per-shutdown-phase: 15s
   r2dbc:
      username: postgres
      password: admin
      url: r2dbc:postgresql://localhost:5432/polardb_order
      pool:
         max-create-connection-time: 2s
         initial-size: 5
         max-size: 10

logging:
   pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
   level:
      io.reactor.netty: DEBUG
      org.springframework.web.reactive.function.client: DEBUG

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
         show-components: always
         probes:
            enabled: true
   info:
      env:
         enabled: true
      java:
         enabled: true
      os:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}

polar:
   catalog-service-uri: http://localhost:9001