name: Acceptance Stage
on:
  workflow_run:
    workflows: ['Commit Stage']
    types: [completed]
    branches: main
concurrency: acceptance

env:
  OWNER: upen28
  REGISTRY: ghcr.io
  IMAGE_NAME: polar-bookshop/order-service
  VERSION: ${{ github.sha }}
  APP_REPO: order-service
  
  DEPLOY_REPO: polar-deployment-2
  

jobs:
  functional:
    name: Functional Acceptance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running functional acceptance tests"
  performance:
    name: Performance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running performance tests"
  security:
    name: Security Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running security tests"
  deliver:
    name: Deliver Release Candidate to Production
    needs: [ functional, performance, security ]
    runs-on: ubuntu-latest
    steps:
      - name: Deliver Application to Production
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ env.OWNER }}/${{ env.DEPLOY_REPO }}
          event-type: app_delivery
          client-payload: '{
            "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}",
            "app_version": "${{ env.VERSION }}", 
            "app_name": "${{ env.APP_REPO }}",
            "app-dir-name": "production" 
            }'              